# High School Academic Achievement
## Dataset Preparation

Predicting students high school final marks using variables of academic performance and some personal features that are stored in the database of the Education Ministry along with some economical, social and demographical indexes retrieved from the files of the National Statistical Body.

In [106]:
import pandas as pd
import numpy as np

In [107]:
df = pd.read_csv('DATA_SET.csv')

In [108]:
df.head()

AcademicYear  N_NoApprovals Nationality Gender  N_Enrollments  Scholarship  \
0            11              0          PT      F              1            0   
1            11              0          PT      F              1            0   
2            12              0          PT      M              1            0   
3            12              0          PT      F              1            1   
4            11              2          PT      F              1            2   

   PermanentIncomeSupport  Computer  InternetAccess  \
0                     NaN      True            True   
1                     NaN      True            True   
2                     NaN     False           False   
3                     2.0     False           False   
4                     1.0     False           False   

                       CourseSubject  UrbanIndex  IncomeIndex  AgingIndex  \
0      Língua Estrangeira I - Inglês       138.4        875.1       146.2   
1  Língua Estrangeira III - Espanhol       138.4        875.1       146.2   
2                       Matemática A      5090.4       1560.6       189.3   
3                           Biologia      5090.4       1560.6       189.3   
4      Língua Estrangeira I - Inglês      5090.4       1560.6       189.3   

   UnemploymentIndex  CulturalLevelIndex  ClassSize  SchoolSize  \
0               9.73               12.77         23         193   
1               9.73               12.77         23         193   
2              11.76               70.93         29         519   
3              11.76               70.93         29         519   
4              11.76               70.93         25         519   

   N_SubjectsEnrolled  FinalMark  
0                   7         10  
1                   7         16  
2                   5         19  
3                   5         16  
4                   7         10

In [109]:
df.shape

(542808, 19)

In [110]:
df.columns

Index(['AcademicYear', 'N_NoApprovals', 'Nationality', 'Gender',
       'N_Enrollments', 'Scholarship', 'PermanentIncomeSupport', 'Computer',
       'InternetAccess', 'CourseSubject', 'UrbanIndex', 'IncomeIndex',
       'AgingIndex', 'UnemploymentIndex', 'CulturalLevelIndex', 'ClassSize',
       'SchoolSize', 'N_SubjectsEnrolled', 'FinalMark'],
      dtype='object')

In [111]:
df['CourseSubject'].unique()

array(['Língua Estrangeira I - Inglês',
       'Língua Estrangeira III - Espanhol', 'Matemática A', 'Biologia',
       'Psicologia B', 'Português', 'Educação Física', 'Sociologia',
       'Ciência Política', 'História A', 'Filosofia', 'Geografia A',
       'Matemática Aplicada às Ciências Sociais', 'Economia C',
       'História da Cultura e das Artes', 'Matemática B',
       'Geometria Descritiva A', 'Desenho A', 'Economia A',
       'Aplicações Informáticas B', 'Física e Química A',
       'Biologia e Geologia', 'Literatura Portuguesa', 'Oficina de Artes',
       'Física', 'Educação Moral e Religiosa', 'Filosofia A',
       'Geografia C', 'História B', 'Língua Estrangeira III - Inglês',
       'Língua Estrangeira II - Francês', 'Química', 'Geologia',
       'Físico-Química A', 'Língua Estrangeira II - Inglês',
       'Língua Estrangeira III - Alemão',
       'Língua Estrangeira I - Espanhol', 'Direito',
       'Língua Estrangeira II - Espanhol', 'Oficina Multimédia B',
       'Formaç

## Subjects with more than 15,000 samples

* Português
* Filosofia
* Língua Estrangeira I - Inglês
* Matemática A
* Física e Química A
* Biologia e Geologia
* Geografia A
* História A
* Biologia
* Psicologia B

In [112]:
subject_names = [ 'Português', 'Filosofia', 'Língua Estrangeira I - Inglês',
                 'Matemática A', 'Física e Química A', 'Biologia e Geologia',
                 'Geografia A', 'História A', 'Biologia', 'Psicologia B']

In [113]:
df.drop(pd.Index(np.where(~df['CourseSubject'].isin(subject_names))[0]), inplace = True)
#df.drop(pd.Index(np.where(df['column'].isin(values))[0]), inplace = True)

In [114]:
df.shape

(362261, 19)

In [115]:
Course_Subject = df['CourseSubject'].unique()
print("Shape per Course Subject:\n")
for i in Course_Subject:
    Subject_i= df[df['CourseSubject']== i]
    print(i, '\t', Subject_i.shape)

Shape per Course Subject:

Língua Estrangeira I - Inglês 	 (54905, 19)
Matemática A 	 (46606, 19)
Biologia 	 (16453, 19)
Psicologia B 	 (16204, 19)
Português 	 (75061, 19)
História A 	 (19767, 19)
Filosofia 	 (57272, 19)
Geografia A 	 (19892, 19)
Física e Química A 	 (28599, 19)
Biologia e Geologia 	 (27502, 19)


In [10]:
Binarised_Features = [ 'AcademicYear', 'Nationality', 'Gender',
                      'Scholarship', 'PermanentIncomeSupport', 'Computer',
                      'InternetAccess' ]

In [11]:
print("Unique values per features to be binarised:\n")
for i in Binarised_Features:
    HE_i= df[i].unique()
    print(i, '\t', HE_i)

Unique values per features to be binarised:

AcademicYear 	 [11 12 10]
Nationality 	 ['PT' 'DE' 'BR' 'ZA' 'AO' 'CH' 'UA' 'RO' 'MD' 'CN' 'VE' 'BY' 'CV' 'RU'
 'IT' 'GB' 'FR' 'CM' 'ST' 'GW' 'NL' 'BB' 'LU' 'US' 'DK' 'ES' 'BE' 'BG'
 'PL' 'AR' 'CO' 'IN' 'TH' 'BD' 'DO' 'PY' 'TR' 'PA' 'KZ' 'CS' 'TL' 'CU'
 'LT' 'MA' 'NO' 'HU' 'EC' 'CA' 'SV' 'KR' 'IQ' 'EE' 'CL' 'MO' 'NP' 'SE' nan
 'MZ' 'UZ' 'SL' 'AD' 'BS' 'AF' 'GE' 'PR' 'PH' 'LV' 'QA' 'IS' 'FI' 'GN'
 'PK' 'AU' 'PE' 'DZ' 'GT' 'NG' 'ZW' 'QU' 'IE' 'AT' 'SN' 'TG' 'EG' 'CI'
 'BJ' 'CG' 'UY' 'ID' 'TJ' 'GQ' 'XR' 'TN' 'IR' 'JP' 'MY' 'SA']
Gender 	 ['F' 'M']
Scholarship 	 [0 1 2]
PermanentIncomeSupport 	 [nan  2.  1.  3.]
Computer 	 [ True False]
InternetAccess 	 [ True False]


In [12]:
df['PermanentIncomeSupport'] = df['PermanentIncomeSupport'].fillna(0)
df['PermanentIncomeSupport'].unique()

array([0., 2., 1., 3.])

In [13]:
df['Nationality'] = df['Nationality'].fillna('Unknown')

In [14]:
df1 = df[df.Nationality =='Unknown']
df1.shape

(6, 19)

In [15]:
df1

AcademicYear  N_NoApprovals Nationality Gender  N_Enrollments  \
116202            11              0     Unknown      F              1   
116203            11              0     Unknown      F              1   
339512            11              0     Unknown      F              1   
350092            11              0     Unknown      F              1   
350440            11              0     Unknown      F              1   
354479            11              0     Unknown      F              1   

        Scholarship  PermanentIncomeSupport  Computer  InternetAccess  \
116202            2                     1.0     False           False   
116203            2                     1.0     False           False   
339512            2                     1.0     False           False   
350092            2                     1.0     False           False   
350440            2                     1.0     False           False   
354479            2                     1.0     False           False   

                        CourseSubject  UrbanIndex  IncomeIndex  AgingIndex  \
116202                   Matemática A      5090.4       1560.6       189.3   
116203  Língua Estrangeira I - Inglês      5090.4       1560.6       189.3   
339512             Física e Química A      5090.4       1560.6       189.3   
350092                      Português      5090.4       1560.6       189.3   
350440                      Filosofia      5090.4       1560.6       189.3   
354479            Biologia e Geologia      5090.4       1560.6       189.3   

        UnemploymentIndex  CulturalLevelIndex  ClassSize  SchoolSize  \
116202              11.76               70.93         17         243   
116203              11.76               70.93         17         243   
339512              11.76               70.93         17         243   
350092              11.76               70.93         17         243   
350440              11.76               70.93         17         243   
354479              11.76               70.93         17         243   

        N_SubjectsEnrolled  FinalMark  
116202                   8         10  
116203                   8         12  
339512                   8         10  
350092                   8         12  
350440                   8         11  
354479                   8         11

In [16]:
print("Unique values per features to be binarised:\n")
for i in Binarised_Features:
    HE_i= df[i].unique()
    print(i, '\t', HE_i)

Unique values per features to be binarised:

AcademicYear 	 [11 12 10]
Nationality 	 ['PT' 'DE' 'BR' 'ZA' 'AO' 'CH' 'UA' 'RO' 'MD' 'CN' 'VE' 'BY' 'CV' 'RU'
 'IT' 'GB' 'FR' 'CM' 'ST' 'GW' 'NL' 'BB' 'LU' 'US' 'DK' 'ES' 'BE' 'BG'
 'PL' 'AR' 'CO' 'IN' 'TH' 'BD' 'DO' 'PY' 'TR' 'PA' 'KZ' 'CS' 'TL' 'CU'
 'LT' 'MA' 'NO' 'HU' 'EC' 'CA' 'SV' 'KR' 'IQ' 'EE' 'CL' 'MO' 'NP' 'SE'
 'Unknown' 'MZ' 'UZ' 'SL' 'AD' 'BS' 'AF' 'GE' 'PR' 'PH' 'LV' 'QA' 'IS'
 'FI' 'GN' 'PK' 'AU' 'PE' 'DZ' 'GT' 'NG' 'ZW' 'QU' 'IE' 'AT' 'SN' 'TG'
 'EG' 'CI' 'BJ' 'CG' 'UY' 'ID' 'TJ' 'GQ' 'XR' 'TN' 'IR' 'JP' 'MY' 'SA']
Gender 	 ['F' 'M']
Scholarship 	 [0 1 2]
PermanentIncomeSupport 	 [0. 2. 1. 3.]
Computer 	 [ True False]
InternetAccess 	 [ True False]


In [17]:
df.columns

Index(['AcademicYear', 'N_NoApprovals', 'Nationality', 'Gender',
       'N_Enrollments', 'Scholarship', 'PermanentIncomeSupport', 'Computer',
       'InternetAccess', 'CourseSubject', 'UrbanIndex', 'IncomeIndex',
       'AgingIndex', 'UnemploymentIndex', 'CulturalLevelIndex', 'ClassSize',
       'SchoolSize', 'N_SubjectsEnrolled', 'FinalMark'],
      dtype='object')

In [18]:
ind_AcademicYear = pd.get_dummies(df['AcademicYear'], prefix='AcYear')

In [19]:
ind_AcademicYear.head()

AcYear_10  AcYear_11  AcYear_12
0          0          1          0
2          0          0          1
3          0          0          1
4          0          1          0
5          0          0          1

In [20]:
ind_AcademicYear1 = ind_AcademicYear.drop('AcYear_10', axis=1)

In [21]:
ind_AcademicYear1.shape

(362261, 2)

In [22]:
df.shape

(362261, 19)

In [23]:
df1 = pd.concat([ind_AcademicYear1, df], axis=1)

In [24]:
df1.shape

(362261, 21)

In [25]:
df=df1.drop('AcademicYear', axis=1)


In [26]:
df.shape

(362261, 20)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362261 entries, 0 to 542807
Data columns (total 20 columns):
AcYear_11                 362261 non-null uint8
AcYear_12                 362261 non-null uint8
N_NoApprovals             362261 non-null int64
Nationality               362261 non-null object
Gender                    362261 non-null object
N_Enrollments             362261 non-null int64
Scholarship               362261 non-null int64
PermanentIncomeSupport    362261 non-null float64
Computer                  362261 non-null bool
InternetAccess            362261 non-null bool
CourseSubject             362261 non-null object
UrbanIndex                362261 non-null float64
IncomeIndex               362261 non-null float64
AgingIndex                362261 non-null float64
UnemploymentIndex         362261 non-null float64
CulturalLevelIndex        362261 non-null float64
ClassSize                 362261 non-null int64
SchoolSize                362261 non-null int64
N_SubjectsEn

In [28]:
N_Enrollments = df['N_Enrollments'].unique()

In [29]:
print("Shape per number of enrollments:\n")
for i in N_Enrollments:
    Enroll_i= df[df['N_Enrollments']== i]
    print(i, '\t', Enroll_i.shape)

Shape per number of enrollments:

1 	 (337279, 20)
2 	 (23357, 20)
3 	 (1502, 20)
5 	 (17, 20)
4 	 (106, 20)


In [30]:
#ind_Enrollments = pd.get_dummies(df['N_Enrollments'], prefix='NEnroll')

In [31]:
#ind_Enrollments.head()

In [32]:
#ind_Enrollments1 = ind_Enrollments.drop('NEnroll_1', axis=1)

In [33]:
#ind_Enrollments1.shape

In [34]:
#df1 = pd.concat([ind_Enrollments1, df], axis=1)

In [35]:
#df1.shape

In [36]:
#df=df1.drop('N_Enrollments', axis=1)

In [37]:
#df.shape

In [38]:
#df.info()

In [39]:
df['Nationality'].unique()

array(['PT', 'DE', 'BR', 'ZA', 'AO', 'CH', 'UA', 'RO', 'MD', 'CN', 'VE',
       'BY', 'CV', 'RU', 'IT', 'GB', 'FR', 'CM', 'ST', 'GW', 'NL', 'BB',
       'LU', 'US', 'DK', 'ES', 'BE', 'BG', 'PL', 'AR', 'CO', 'IN', 'TH',
       'BD', 'DO', 'PY', 'TR', 'PA', 'KZ', 'CS', 'TL', 'CU', 'LT', 'MA',
       'NO', 'HU', 'EC', 'CA', 'SV', 'KR', 'IQ', 'EE', 'CL', 'MO', 'NP',
       'SE', 'Unknown', 'MZ', 'UZ', 'SL', 'AD', 'BS', 'AF', 'GE', 'PR',
       'PH', 'LV', 'QA', 'IS', 'FI', 'GN', 'PK', 'AU', 'PE', 'DZ', 'GT',
       'NG', 'ZW', 'QU', 'IE', 'AT', 'SN', 'TG', 'EG', 'CI', 'BJ', 'CG',
       'UY', 'ID', 'TJ', 'GQ', 'XR', 'TN', 'IR', 'JP', 'MY', 'SA'],
      dtype=object)

In [40]:
df['Nationality']=df['Nationality'].map({'PT':0, 'DE':1, 'BR':1, 'ZA':1, 'AO':1, 'CH':1, 'UA':1, 'RO':1, 'MD':1, 'CN':1, 'VE':1,
       'BY':1, 'CV':1, 'RU':1, 'IT':1, 'GB':1, 'FR':1, 'CM':1, 'ST':1, 'GW':1, 'NL':1, 'BB':1,
       'LU':1, 'US':1, 'DK':1, 'ES':1, 'BE':1, 'BG':1, 'PL':1, 'AR':1, 'CO':1, 'IN':1, 'TH':1,
       'BD':1, 'DO':1, 'PY':1, 'TR':1, 'PA':1, 'KZ':1, 'CS':1, 'TL':1, 'CU':1, 'LT':1, 'MA':1,
       'NO':1, 'HU':1, 'EC':1, 'CA':1, 'SV':1, 'KR':1, 'IQ':1, 'EE':1, 'CL':1, 'MO':1, 'NP':1,
       'SE':1, 'Unknown':1, 'MZ':1, 'UZ':1, 'SL':1, 'AD':1, 'BS':1, 'AF':1, 'GE':1, 'PR':1,
       'PH':1, 'LV':1, 'QA':1, 'IS':1, 'FI':1, 'GN':1, 'PK':1, 'AU':1, 'PE':1, 'DZ':1, 'GT':1,
       'NG':1, 'ZW':1, 'QU':1, 'IE':1, 'AT':1, 'SN':1, 'TG':1, 'EG':1, 'CI':1, 'BJ':1, 'CG':1,
       'UY':1, 'ID':1, 'TJ':1, 'GQ':1, 'XR':1, 'TN':1, 'IR':1, 'JP':1, 'MY':1, 'SA':1})

In [41]:
#df.Nationality = df.Nationality.astype()

In [42]:
df['Nationality'].unique()

array([0, 1], dtype=int64)

In [43]:
ind_Gender = pd.get_dummies(df['Gender'], prefix='Gender')

In [44]:
ind_Gender.head()

Gender_F  Gender_M
0         1         0
2         0         1
3         1         0
4         1         0
5         0         1

In [45]:
ind_Gender1 = ind_Gender.drop('Gender_F', axis=1)

In [46]:
ind_Gender1.shape

(362261, 1)

In [47]:
df.shape

(362261, 20)

In [48]:
df1 = pd.concat([ind_Gender1, df], axis=1)

In [49]:
df1.shape

(362261, 21)

In [50]:
df=df1.drop('Gender', axis=1)

In [51]:
df.shape

(362261, 20)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362261 entries, 0 to 542807
Data columns (total 20 columns):
Gender_M                  362261 non-null uint8
AcYear_11                 362261 non-null uint8
AcYear_12                 362261 non-null uint8
N_NoApprovals             362261 non-null int64
Nationality               362261 non-null int64
N_Enrollments             362261 non-null int64
Scholarship               362261 non-null int64
PermanentIncomeSupport    362261 non-null float64
Computer                  362261 non-null bool
InternetAccess            362261 non-null bool
CourseSubject             362261 non-null object
UrbanIndex                362261 non-null float64
IncomeIndex               362261 non-null float64
AgingIndex                362261 non-null float64
UnemploymentIndex         362261 non-null float64
CulturalLevelIndex        362261 non-null float64
ClassSize                 362261 non-null int64
SchoolSize                362261 non-null int64
N_SubjectsEnro

In [53]:
df['Scholarship'].unique()

array([0, 1, 2], dtype=int64)

In [54]:
df.Scholarship.value_counts()

0    263565
1     51895
2     46801
Name: Scholarship, dtype: int64

In [55]:
ind_Scholarship = pd.get_dummies(df['Scholarship'], prefix='Scholarship')
ind_Scholarship.head()


Scholarship_0  Scholarship_1  Scholarship_2
0              1              0              0
2              1              0              0
3              0              1              0
4              0              0              1
5              1              0              0

In [56]:
ind_Scholarship1 = ind_Scholarship.drop('Scholarship_0', axis=1);
ind_Scholarship1.shape

(362261, 2)

In [57]:
df.shape

(362261, 20)

In [58]:
df1 = pd.concat([ind_Scholarship1, df], axis=1)
df1.shape

(362261, 22)

In [59]:
df=df1.drop('Scholarship', axis=1)
df.shape

(362261, 21)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362261 entries, 0 to 542807
Data columns (total 21 columns):
Scholarship_1             362261 non-null uint8
Scholarship_2             362261 non-null uint8
Gender_M                  362261 non-null uint8
AcYear_11                 362261 non-null uint8
AcYear_12                 362261 non-null uint8
N_NoApprovals             362261 non-null int64
Nationality               362261 non-null int64
N_Enrollments             362261 non-null int64
PermanentIncomeSupport    362261 non-null float64
Computer                  362261 non-null bool
InternetAccess            362261 non-null bool
CourseSubject             362261 non-null object
UrbanIndex                362261 non-null float64
IncomeIndex               362261 non-null float64
AgingIndex                362261 non-null float64
UnemploymentIndex         362261 non-null float64
CulturalLevelIndex        362261 non-null float64
ClassSize                 362261 non-null int64
SchoolSize    

In [61]:
# df['Scholarship']=df['Scholarship'].map({0 :0, 1 :1, 2 :1})
# 0 means no scholarship
# df['Scholarship'].unique()

In [62]:
df['PermanentIncomeSupport'].unique()

array([0., 2., 1., 3.])

In [63]:
df.PermanentIncomeSupport.value_counts()

0.0    263155
2.0     51473
1.0     43732
3.0      3901
Name: PermanentIncomeSupport, dtype: int64

In [64]:
#df['PermanentIncomeSupport']=df['PermanentIncomeSupport'].map({0 :0, 1 :1, 2 :1, 3:1})
# 0 means no support
#df['PermanentIncomeSupport'].unique()

In [65]:
df.PermanentIncomeSupport = df.PermanentIncomeSupport.astype(int)

In [66]:
ind_PermanentIncomeSupport = pd.get_dummies(df['PermanentIncomeSupport'], prefix='PermanentIncomeSupport')
ind_PermanentIncomeSupport.head()

PermanentIncomeSupport_0  PermanentIncomeSupport_1  \
0                         1                         0   
2                         1                         0   
3                         0                         0   
4                         0                         1   
5                         1                         0   

   PermanentIncomeSupport_2  PermanentIncomeSupport_3  
0                         0                         0  
2                         0                         0  
3                         1                         0  
4                         0                         0  
5                         0                         0

In [67]:
ind_PermanentIncomeSupport1 = ind_PermanentIncomeSupport.drop('PermanentIncomeSupport_0', axis=1);
ind_PermanentIncomeSupport1.shape

(362261, 3)

In [68]:
df.shape

(362261, 21)

In [69]:
df1 = pd.concat([ind_PermanentIncomeSupport1, df], axis=1)
df1.shape

(362261, 24)

In [70]:
df=df1.drop('PermanentIncomeSupport', axis=1)
df.shape

(362261, 23)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362261 entries, 0 to 542807
Data columns (total 23 columns):
PermanentIncomeSupport_1    362261 non-null uint8
PermanentIncomeSupport_2    362261 non-null uint8
PermanentIncomeSupport_3    362261 non-null uint8
Scholarship_1               362261 non-null uint8
Scholarship_2               362261 non-null uint8
Gender_M                    362261 non-null uint8
AcYear_11                   362261 non-null uint8
AcYear_12                   362261 non-null uint8
N_NoApprovals               362261 non-null int64
Nationality                 362261 non-null int64
N_Enrollments               362261 non-null int64
Computer                    362261 non-null bool
InternetAccess              362261 non-null bool
CourseSubject               362261 non-null object
UrbanIndex                  362261 non-null float64
IncomeIndex                 362261 non-null float64
AgingIndex                  362261 non-null float64
UnemploymentIndex           362261

In [72]:
df['Computer'].unique()

array([ True, False])

In [73]:
df['InternetAccess'].unique()

array([ True, False])

In [74]:
df.Computer = df.Computer.astype(int)
df.InternetAccess = df.InternetAccess.astype(int)

In [75]:
df['Computer'].unique()

array([1, 0], dtype=int64)

In [76]:
df['InternetAccess'].unique()

array([1, 0], dtype=int64)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362261 entries, 0 to 542807
Data columns (total 23 columns):
PermanentIncomeSupport_1    362261 non-null uint8
PermanentIncomeSupport_2    362261 non-null uint8
PermanentIncomeSupport_3    362261 non-null uint8
Scholarship_1               362261 non-null uint8
Scholarship_2               362261 non-null uint8
Gender_M                    362261 non-null uint8
AcYear_11                   362261 non-null uint8
AcYear_12                   362261 non-null uint8
N_NoApprovals               362261 non-null int64
Nationality                 362261 non-null int64
N_Enrollments               362261 non-null int64
Computer                    362261 non-null int32
InternetAccess              362261 non-null int32
CourseSubject               362261 non-null object
UrbanIndex                  362261 non-null float64
IncomeIndex                 362261 non-null float64
AgingIndex                  362261 non-null float64
UnemploymentIndex           3622

In [78]:
df['N_NoApprovals'].unique()

array([  0,   2,   1,   4,  -1,   3,  -3,  -2,   5,   6, -16,  31,  -8,
        11,  -9, -21, -10,  10,  24,  33,  12,  32,   7,  20,   8],
      dtype=int64)

In [79]:
df.N_NoApprovals.value_counts()

 0     277333
 1      62584
 2      15146
-1       3322
 3       3110
 4        537
-2         70
 5         62
 6         18
 10        17
-3         14
-10         8
 24         6
 11         5
 20         5
 12         3
-21         3
-8          3
-16         3
-9          3
 7          2
 31         2
 32         2
 33         2
 8          1
Name: N_NoApprovals, dtype: int64

In [80]:
df['N_NoApprovals']=df['N_NoApprovals'].map({0:0, 1:1, 2:2, -1:0, 3:3, 4:4, -2:0, 5:4, 6:4, -3:0,
                                             -10:0, -21:0, -8:0, -16:0, -9:0})

In [81]:
df.N_NoApprovals.value_counts()

0.0    280759
1.0     62584
2.0     15146
3.0      3110
4.0       617
Name: N_NoApprovals, dtype: int64

In [82]:
df['N_NoApprovals'].unique()

array([ 0.,  2.,  1.,  4.,  3., nan])

In [83]:
# df.isna().sum()
df['N_NoApprovals'].isna().sum()

45

In [84]:
df.dropna(inplace=True)

In [85]:
df.shape

(362216, 23)

In [86]:
df.N_NoApprovals = df.N_NoApprovals.astype(int)

In [87]:
df['ClassSize'].min()

1

In [88]:
df['ClassSize'].unique()

array([23, 29, 25, 30, 34, 28, 31, 33, 24, 27, 22, 26, 18, 19, 36, 32, 15,
       21, 49, 17, 16, 20, 50, 12,  9, 14, 35, 11, 10,  7, 38, 13, 63, 37,
        2,  8,  4,  1,  5,  6, 44, 42,  3, 46, 53, 47, 39], dtype=int64)

In [89]:
df['ClassSize'].value_counts()

30    40113
29    37023
28    36673
26    34289
27    33415
25    24689
31    22868
24    18988
23    15327
32    13823
22    12565
21    11217
20    10441
19     8947
33     8293
18     5497
17     4117
34     3931
16     3184
15     3136
14     2415
36     1742
35     1717
13     1485
12     1351
11     1017
37      741
9       553
10      490
38      342
53      281
39      244
8       203
49      199
7       159
46      124
63      114
42      113
50       97
5        80
6        53
44       45
1        40
47       26
4        23
2        16
3        10
Name: ClassSize, dtype: int64

In [90]:
#df1 = df[df.Nationality =='Unknown']
df=df[df.ClassSize >= 5]

In [91]:
df.shape

(362127, 23)

In [92]:
df['SchoolSize'].min()

11

In [93]:
#df['SchoolSize'].unique()

In [94]:
df['N_SubjectsEnrolled'].min()

1

In [95]:
df['N_SubjectsEnrolled'].unique()

array([ 7,  5,  2,  4,  8,  6,  1,  3,  9, 10, 11, 12, 13], dtype=int64)

In [96]:
df['N_SubjectsEnrolled'].value_counts()

7     200226
5      93521
8      31328
6      17085
4       9522
1       4343
3       2561
2       2429
9        631
10       290
11       167
12        18
13         6
Name: N_SubjectsEnrolled, dtype: int64

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362127 entries, 0 to 542807
Data columns (total 23 columns):
PermanentIncomeSupport_1    362127 non-null uint8
PermanentIncomeSupport_2    362127 non-null uint8
PermanentIncomeSupport_3    362127 non-null uint8
Scholarship_1               362127 non-null uint8
Scholarship_2               362127 non-null uint8
Gender_M                    362127 non-null uint8
AcYear_11                   362127 non-null uint8
AcYear_12                   362127 non-null uint8
N_NoApprovals               362127 non-null int32
Nationality                 362127 non-null int64
N_Enrollments               362127 non-null int64
Computer                    362127 non-null int32
InternetAccess              362127 non-null int32
CourseSubject               362127 non-null object
UrbanIndex                  362127 non-null float64
IncomeIndex                 362127 non-null float64
AgingIndex                  362127 non-null float64
UnemploymentIndex           3621

In [98]:
# df.to_excel("PREPARED_DS_V1.xlsx", sheet_name='DATASET')

In [99]:
df['Gender_M__ClassSize'] = df['Gender_M'] * df['ClassSize']
df.head()

PermanentIncomeSupport_1  PermanentIncomeSupport_2  \
0                         0                         0   
2                         0                         0   
3                         0                         1   
4                         1                         0   
5                         0                         0   

   PermanentIncomeSupport_3  Scholarship_1  Scholarship_2  Gender_M  \
0                         0              0              0         0   
2                         0              0              0         1   
3                         0              1              0         0   
4                         0              0              1         0   
5                         0              0              0         1   

   AcYear_11  AcYear_12  N_NoApprovals  Nationality  ...  UrbanIndex  \
0          1          0              0            0  ...       138.4   
2          0          1              0            0  ...      5090.4   
3          0          1              0            0  ...      5090.4   
4          1          0              2            0  ...      5090.4   
5          0          1              0            0  ...      5090.4   

   IncomeIndex  AgingIndex UnemploymentIndex  CulturalLevelIndex  ClassSize  \
0        875.1       146.2              9.73               12.77         23   
2       1560.6       189.3             11.76               70.93         29   
3       1560.6       189.3             11.76               70.93         29   
4       1560.6       189.3             11.76               70.93         25   
5       1560.6       189.3             11.76               70.93         29   

   SchoolSize  N_SubjectsEnrolled  FinalMark  Gender_M__ClassSize  
0         193                   7         10                    0  
2         519                   5         19                   29  
3         519                   5         16                    0  
4         519                   7         10                    0  
5         519                   5         17                   29  

[5 rows x 24 columns]

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 362127 entries, 0 to 542807
Data columns (total 24 columns):
PermanentIncomeSupport_1    362127 non-null uint8
PermanentIncomeSupport_2    362127 non-null uint8
PermanentIncomeSupport_3    362127 non-null uint8
Scholarship_1               362127 non-null uint8
Scholarship_2               362127 non-null uint8
Gender_M                    362127 non-null uint8
AcYear_11                   362127 non-null uint8
AcYear_12                   362127 non-null uint8
N_NoApprovals               362127 non-null int32
Nationality                 362127 non-null int64
N_Enrollments               362127 non-null int64
Computer                    362127 non-null int32
InternetAccess              362127 non-null int32
CourseSubject               362127 non-null object
UrbanIndex                  362127 non-null float64
IncomeIndex                 362127 non-null float64
AgingIndex                  362127 non-null float64
UnemploymentIndex           3621

In [101]:
df.columns.values

array(['PermanentIncomeSupport_1', 'PermanentIncomeSupport_2',
       'PermanentIncomeSupport_3', 'Scholarship_1', 'Scholarship_2',
       'Gender_M', 'AcYear_11', 'AcYear_12', 'N_NoApprovals',
       'Nationality', 'N_Enrollments', 'Computer', 'InternetAccess',
       'CourseSubject', 'UrbanIndex', 'IncomeIndex', 'AgingIndex',
       'UnemploymentIndex', 'CulturalLevelIndex', 'ClassSize',
       'SchoolSize', 'N_SubjectsEnrolled', 'FinalMark',
       'Gender_M__ClassSize'], dtype=object)

In [102]:
df = df[['PermanentIncomeSupport_1', 'PermanentIncomeSupport_2',
       'PermanentIncomeSupport_3', 'Scholarship_1', 'Scholarship_2',
       'Gender_M', 'AcYear_11', 'AcYear_12', 'N_NoApprovals',
       'Nationality', 'N_Enrollments', 'Computer', 'InternetAccess',
       'CourseSubject', 'UrbanIndex', 'IncomeIndex', 'AgingIndex',
       'UnemploymentIndex', 'CulturalLevelIndex', 'ClassSize',
       'SchoolSize', 'N_SubjectsEnrolled', 'Gender_M__ClassSize', 'FinalMark']]

In [103]:
df.to_excel("PREPARED_DS_V1.xlsx", sheet_name='DATASET')

In [104]:
df1 = df.iloc[:, :23]
df1.columns.values

array(['PermanentIncomeSupport_1', 'PermanentIncomeSupport_2',
       'PermanentIncomeSupport_3', 'Scholarship_1', 'Scholarship_2',
       'Gender_M', 'AcYear_11', 'AcYear_12', 'N_NoApprovals',
       'Nationality', 'N_Enrollments', 'Computer', 'InternetAccess',
       'CourseSubject', 'UrbanIndex', 'IncomeIndex', 'AgingIndex',
       'UnemploymentIndex', 'CulturalLevelIndex', 'ClassSize',
       'SchoolSize', 'N_SubjectsEnrolled', 'Gender_M__ClassSize'],
      dtype=object)

In [105]:
df1 = df.iloc[:, -1]
df1.head()

0    10
2    19
3    16
4    10
5    17
Name: FinalMark, dtype: int64